### ISSUE TITLE
priorityToTrafficClassMappingList to be added

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanFd#12]
The vlanInterfaceConfiguration::priorityToTrafficClassMappingList attribute cannot be configured on interface level at approximately 50% of known devices.
Some other indicate support on device or VLAN bridge layer.
Assuming that most devices are supporting just one VLAN bridge per device, it is proposed to add the same configuration attributes to the VlanFd.

Proposal:
vlanFdConfiguration::priorityToTrafficClassMappingList attribute according to existing definition in VlanInterface to be added.
PriorityToTrafficClassMappingType datatype according to existing definition in VlanInterface to be added.

**Comment by openBackhaul** [comment]
**Potential Proposal:**
Adding the following elements to the VlanInterface modeling:
- vlanInterfaceCapability::priorityToTrafficClassMappingIsAvail : boolean attribute incl. "true = configuring the mapping of the Priority values into Traffic Classes (queues) is available for individual interfaces. (If similar configuration would be available on switch and on interface level, the interface specific configuration would overwrite the configuration made on switch level.)" comment.

Adding the following elements to the VlanFd modeling: 
- vlanFdCapability::priorityToTrafficClassMappingIsAvail : boolean attribute incl. "true = configuring the mapping of the Priority values into Traffic Classes (queues) is available as a configuration, which is common to all interfaces at the switch." comment.
- vlanFdConfiguration::priorityToTrafficClassMappingList attribute according to existing definition in VlanInterface
- PriorityToTrafficClassMappingType datatype according to existing definition in VlanInterface

**Comment by demx8as6** [comment]
**Decision on the 5G-xhaul-call 29th of September 2021:**
Adding the following elements to the VlanInterface modeling:

vlanInterfaceCapability::priorityToTrafficClassMappingIsAvail : boolean attribute incl. "true = configuring the mapping of the Priority values into Traffic Classes (queues) is available for individual interfaces. (If similar configuration would be available on switch and on interface level, the interface specific configuration would overwrite the configuration made on switch level.)" comment.
Adding the following elements to the VlanFd modeling:

vlanFdCapability::priorityToTrafficClassMappingIsAvail : boolean attribute incl. "true = configuring the mapping of the Priority values into Traffic Classes (queues) is available as a configuration, which is common to all interfaces at the switch." comment.
vlanFdConfiguration::priorityToTrafficClassMappingList attribute according to existing definition in VlanInterface
PriorityToTrafficClassMappingType datatype according to existing definition in VlanInterface

**Comment by openBackhaul** [comment]
**Following elements have been added to the VlanFd modeling:**  
* vlanFdCapability::priorityToTrafficClassMappingIsAvail : boolean attribute incl. "true = configuring the mapping of the Priority values into Traffic Classes (queues) is available as a configuration, which is common to all interfaces at the switch." comment.
* vlanFdConfiguration::priorityToTrafficClassMappingList attribute according to existing definition in VlanInterface
* PriorityToTrafficClassMappingType datatype according to existing definition

**Comment by openBackhaul** [comment]
**Following element has been added to the VlanInterface modeling:**  
* vlanInterfaceCapability::priorityToTrafficClassMappingIsAvail : boolean attribute incl. "true = configuring the mapping of the Priority values into Traffic Classes (queues) is available for individual interfaces. (If similar configuration would be available on switch and on interface level, the interface specific configuration would overwrite the configuration made on switch level.)" comment.

**Comment by openBackhaul** [comment]
Solved with VlanFd_1.0.0-tsp.220407.1740.
