### ISSUE TITLE
RPC operation parameters should be mandatory

### ISSUE THREAD

**Issue by michbin** [openBackhaul/vlanFd#13]
The input parameters for the `create-vlan-fc` and `delete-vlan-fc` operations should be mandatory.
Such a condition can be checked by the Netconf server and thus makes application logic simpler.

**Comment by openBackhaul** [comment]
The attributes at the operations are marked to be mandatory in the UML (it's the default).

After checking for conses in the group, the UML2YANG would have to be complemented.

**Comment by openBackhaul** [comment]
**Update made during Architecture call on 16th of September 2021:**
Prathiba stated:
- Adding mandatory statement into the YANG is already implemented in the UML2YANG tool.
- It requires the multiplicity of the parameters to be [1] in the UML.
- The functionality has already been tested while translating the firmware modeling.

Checking the VlanFd modeling resulted in multiplicity of the parameters to be [1] in all cases.

Issue can be closed after mandatory statements could be found in officially provided YANG.

**Comment by openBackhaul** [comment]
Solved with VlanFd_1.0.0-tsp.220407.1740.
