### ISSUE TITLE
create-vlan-fc: Inconsistent description (make it idempotent)

### ISSUE THREAD

**Issue by michbin** [openBackhaul/vlanFd#14]
The description of the `create-vlan-fc` operation requires that an error is to be reported "if a VlanFc with this VLAN ID would already exist". On the other hand the `created-vlan-fc` output parameter shall contain "the VLAN (either newly created or _already existing_)". This is a contradiction.
The descriptions should be aligned.

**Comment by openBackhaul** [comment]
Proposal:
"...#[onf:VLAN already exists.]#, if a VlanFc with this VLAN ID would already exist. ..." to be deleted from the comment.
As a result the operation should be idempotent.

**Comment by openBackhaul** [comment]
Solved with VlanFd_1.0.0-tsp.220407.1740.
