### ISSUE TITLE
component-id lack a default value

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanFd#15]
Proposal:
Adding the following default value VlanFdCapability::component-id : Integer = -1

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 29th of September 2021:**
Adding default value -1 => VlanFdCapability::componentId : Integer = -1

**Comment by demx8as6** [comment]
**Decision on 5G-xhaul call on 29th of September 2021**:
Adding default value -1 => VlanFdCapability::componentId : Integer = -1

**Comment by openBackhaul** [comment]
Solved with VlanFd_1.0.0-tsp.220407.1740.
