### ISSUE TITLE
protocolGroupType::llcAddressList : String cannot be addressed

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanFd#16]
protocolGroupType::llcAddressList as a list of datatype String cannot be directly addressed.

List attributes cannot be addressed.
Individual entries can also not be addressed, because bare list of Strings does not offer key values to be addressed.

If required to be a list, changing towards a composed datatype having an additional index attribute should be considered.

**Comment by openBackhaul** [comment]
**Status of discussion during Architecture call on 16th of September 2021:**
Potential solution might be creating a composed llcAddressType datatype comprising llcAddressIndex : Integer as a key attribute and llcAddress : String for holding the value.

But the following aspects shall be clarified before deciding:
- Is there a way of retrieving the key attribute's values?
- Wouldn't it suffice to define the llcAddressType to just contain the llcAddress and to define it to be the key attribute?

**Comment by demx8as6** [comment]
Today:

```
leaf-list llc-address-list {
      type string;
      default "LLC Address not yet defined.";
      description
        "Only effective if (protocolFrameFormat==LLC_OTHER). A pair of ISO/IEC 8802-2 DSAP and SSAP address field values, for matching frame formats of LLC_Other. The canonical representation uses uppercase characters. Pattern '[0-9a-fA-F]{2}-[0-9a-fA-F]{2}'. Name in ieee802-dot1q-bridge.yang: llc-address.";
    }
```

Potential future model
```
list llc-address-list {
      key llc-address
      leaf llc-address {
         type string;
         description "TODO";
      } ;
      // default "LLC Address not yet defined."; // [sko] no default of key as they are mandatory
      description
        "Only effective if (protocolFrameFormat==LLC_OTHER). A pair of ISO/IEC 8802-2 DSAP and SSAP address field values, for matching frame formats of LLC_Other. The canonical representation uses uppercase characters. Pattern '[0-9a-fA-F]{2}-[0-9a-fA-F]{2}'. Name in ieee802-dot1q-bridge.yang: llc-address.";
    }
```
Note - the sketch above should be enhanced - a yang uses statement should refer to a yang grouping statement.

**Comment by demx8as6** [comment]
Please check - if the idea above is going into the "right" direction.
@PrathibaJee : please check capability of tooling for string pattern

**Comment by PrathibaJee** [comment]
The UML2YANG tool doesn't have the capability to generate a "pattern" sub-statement for the type string.
We have to enhance the tool to support the mapping (OpenModelAttribute::valueR
ange --> pattern).

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 13th of April 2022:**  

- creating a new LlcAddressType datatype
- adding a new LlcAddressType :: llcAddressIndex : Int8 [1] attribute and define partOfObjectKey==1
- adding a new LlcAddressType :: llcAddress : String [1] = "LLC Address not yet defined." attribute 
- changing datatype of protocolGroupType :: llcAddressList from String to LlcAddressType  

![image](https://user-images.githubusercontent.com/46722892/160809085-ec68e120-b046-47b1-a989-1bfe80f78ce3.png)

**Comment by openBackhaul** [comment]
**Reconsideration**
Alex explained that lists of bare Strings could be handled like this:
* GET   https://......./protocolGroupList=1234?fields=llcAddressList
* DELETE   https://......./protocolGroupList=1234/llcAddressList=StringWhichIsToBeDeleted
* PUT   https://......./protocolGroupList=1234/llcAddressList=StringWhichIsToBeAdded
  * body: { llcAddressList=StringWhichIsToBeAdded }

Based on this, there no benefit from creating a composed datatype as proposed above.

**So the DMIP call on 7th of April 2022, is recommending**
* to vote against the above proposal at the 5G-xhaul call on 13th of April 2022
* to keep the attribute as is and 
* close the issue without further activity.

**Comment by openBackhaul** [comment]
VlanFd_1.0.0-tsp.220407.1740 has been created according to the recommendation made by DMIP call on 7th of April.

**Comment by demx8as6** [comment]
Based on explanation by AlexS regarding usage of leaf-list this issue can be closed without any chance.

**Comment by openBackhaul** [comment]
According to recommendation made by DMIP call on 7th of April issue will be closed without changes on the modeling.
