### ISSUE TITLE
delete-vlan-fc to be made idempotent

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanFd#17]
Following the attempt to define idempotent operations the error messaging of the delete-vlan-id operation should be changed.
If the VlanFc, which is referenced for being deleted, would not exist, no error shall be indicated, because the wished status is already implemented.

Proposal: 
The current comment : "#[onf:Referenced object is invalid.]#, if the referenced ForwardingConstruct does not exist or does not belong to the VLAN layer." to be changed to "#[onf:Referenced object is invalid.]#, if the referenced ForwardingConstruct does not belong to the VLAN layer."

**Comment by demx8as6** [comment]
// TODO @demx8as6 : create an official proposal for approval on Oct 5th

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 13th of April 2022:**  

It is aspired that all operations on the NETCONF interface of the devices are idempotent.
This includes a delete operation addressing an object, which is not existing, not being answered by an error message.
In these regards, a comment at an existing operation (and the implementation of the operation) has to be corrected.
The comment at the deleteVlanFc() operation shall be changed from:  
"#[onf:Referenced object is invalid.]#, if the referenced ForwardingConstruct does not exist or does not belong to the VLAN layer."  
to  
"#[onf:Referenced object is invalid.]#, if the referenced ForwardingConstruct does not belong to the VLAN layer."

**Comment by openBackhaul** [comment]
VlanFd_1.0.0-tsp.220407.1740 has already been adjusted subject to this decision.

**Comment by openBackhaul** [comment]
**Decision made on the 5G-xhaul call on 13th of April 2022:**  

The comment at the deleteVlanFc() operation shall be changed from:  
"#[onf:Referenced object is invalid.]#, if the referenced ForwardingConstruct does not exist or does not belong to the VLAN layer."  
to  
"#[onf:Referenced object is invalid.]#, if the referenced ForwardingConstruct does not belong to the VLAN layer."

(Which has already been anticipated in VlanFd_1.0.0-tsp.220407.1740.)
