### ISSUE TITLE
protocol-frame-format-type:: PROTOCOL_FRAME_FORMAT_TYPE_SNAP8021H incorrect _

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanFd#18]
The  "PROTOCOL_FRAME_FORMAT_TYPE_SNAP8021H " value of the protocol-frame-format-type enumeration has an unnecessary blank at the end in the UML. This results in a "_" at the end in the YANG.

Proposal:
The blank shall be removed in the UML. 
So the "_" will no longer occur in the YANG.

**Comment by demx8as6** [comment]
according to IF call 2021-09-21 we consider this as a simple "bug" which can be corrected without further approval by ONF 5G-xHaul

**Comment by openBackhaul** [comment]
Solved with VlanFd_1.0.0-tsp.220407.1740.
