### ISSUE TITLE
Unconditional augment

### ISSUE THREAD

**Issue by michbin** [openBackhaul/vlanFd#2]
The vlan-fd-1-0 release 2020-08-20 augments the `forwarding-domain` element without any condition. That is, any `forwarding-domain` instance will have VLAN FD properties.

**Comment by openBackhaul** [comment]
The following code has been added to the vlan-fd-1-0.yang:

  identity LAYER_PROTOCOL_NAME_TYPE_VLAN_LAYER {
    base core-model:LAYER_PROTOCOL_NAME_TYPE;
    description
      "none";
  }

  augment "/core-model:control-construct/core-model:forwarding-domain" {
    when "derived-from-or-self(./core-model:layer-protocol-name, 'vlan-fd:LAYER_PROTOCOL_NAME_TYPE_VLAN_LAYER')";
    uses vlan-fd-spec;
    description
      "none";
  }
