### ISSUE TITLE
Deleting maintenance timer related attributes

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanFd#6]
Only one device model supports the maintenanceTimer attribute at the VlanFd.
(Presumably, limited support of the timer is caused by the fact that there are no maintenance features to be timed out at this object.)

It is proposed to delete the following attributes from the modelings:
- VlanFdCapability:: maintenanceTimerRange
- VlanFdConfiguration:: maintenanceTimer

**Comment by demx8as6** [comment]
2020-10-21: Agreed as proposed!

**Comment by openBackhaul** [comment]
UML changed accordingly.
