### ISSUE TITLE
Deleting fdIsOn and related attributes

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanFd#7]
During screening results of a query it became obvious that VlanFdConfiguration::fdIsOn is not supported by any of the device models, which are participating at the TSP.

Therefore it is proposed to delete the following attributes from the VlanFd modeling:
•	VlanFdCapability::adminShutDownIsAvail
•	VlanFdConfiguration::fdIsOn

**Comment by demx8as6** [comment]
2020-10-21: Agreed as proposed!

**Comment by openBackhaul** [comment]
UML changed accordingly.
