### ISSUE TITLE
Supporting VlanFc Creation with proper UUID

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanFd#8]
While configuring a new VLAN, means instantiating a new VlanFc, the ForwardingConstruct object of the to be created VlanFc has to contain some value in its uuid attribute (because it is the key attribute in the ForwardingDomain::_fc [*] attribute).
Problem: The Application cannot anticipate the UUID value, which will be assigned by the Device to the ForwardingConstruct object.
Idea: The Device shall tell the Application, which UUID value to be used while instantiating the VlanFc.
In the specific case of the VLAN, most Devices are assigning UUID values to the ForwardingConstruct object, which are somehow containing the VLAN ID of the VLAN. So for enabling the Device to tell the to be used UUID value, the Device has to be informed about the VLAN ID, which is intended to be used.

Proposal:
A VlanFdConfiguration::vlanIdOfToBeCreatedVlan : INT64 [1] = -1 attribute shall be added.

A nextVlanFcUuidType datatype shall be created.
A nextVlanFcUuidType::vlanIdOfToBeCreatedVlanFc : INT64 [1] = -1 attribute shall be added. 
A nextVlanFcUuidType::uuidOfToBeCreatedVlanFc : String = "UUID not yet created." attribute shall be added.

A VlanFdStatus::nextVlanFcUuid : nextVlanFcUuidType [1] attribute shall be added.

As soon as some value has been successfully configured into the VlanFdConfiguration::vlanIdOfToBeCreatedVlan attribute, the VlanFdStatus::nextVlanFcUuid::vlanIdOfToBeCreatedVlanFc attribute shall represent the exact same value and the VlanFdStatus::nextVlanFcUuid::uuidOfToBeCreatedVlanFc shall contain the corresponding UUID value, which is to be used while instantiating the VlanFc.

**Comment by ThomasSchulzeTelefonica** [comment]
Is there any sequence diagram availbale where the concrete interaction between application and device is visible? The reason behind my question is the different interpretation of Idea and proposal on my side, not being present during the disucssions leading to this proposal.
The formulated Idea implies for me that the Application has to interact twice with the device (first time requesting in general to create a VLAN with a dedicated VLAN-ID, then the device will send back the to be used UUID for this VLAN and at the end the Application has to send the full request containing both VLAN-ID and UUID to device back. But reading the description of the proposal I would assume that the UUID problem will be solved device internally (with the poper modell and behaviour implemented) and device will send back only successful configuration notification of the requested VLAN together with the created/used UUID.

**Comment by openBackhaul** [comment]
Sequence:
Application is PUTting the wished VLAN ID to VlanFdConfiguration::vlanIdOfToBeCreatedVlan.
Device is changing nextVlanFcUuidType::vlanIdOfToBeCreatedVlanFc to this VLAN ID.
Device is changing nextVlanFcUuidType::uuidOfToBeCreatedVlanFc to the proper UUID.
Application is getting nextVlanFcUuidType::vlanIdOfToBeCreatedVlanFc and uuidOfToBeCreatedVlanFc.
Application is comparing got vlanIdOfToBeCreatedVlanFc with wished VLAN,
if equal Application uses uuidOfToBeCreatedVlanFc for creating the VlanFc.

**Comment by michbin** [comment]
I see a number of issues:

1. **Modeling aspects**
The proposal mixes different types of data into one object: (a) data which describes the characteristics of the managed resource in the device (here: VLAN Forwarding Domain); (b) data which controls the behavior of the device.

1. **Non-atomic operation**
The procedure for creating a VLAN FC requires several independent steps, that is, it is not [atomic](https://en.wikipedia.org/wiki/Atomicity_(database_systems)) (DE: [atomar](https://de.wikipedia.org/wiki/Atomar#Informatik)). The resulting behavior may be error-prone and confusing, in particular when simultaneous requests from different clients are processed.

**Comment by openBackhaul** [comment]
During parallel discussions, the idea of using an RPC has been born.
Issue to continue.

**Comment by openBackhaul** [comment]
Solved by defining the createVlanFc() operation.
